FullScreenMario.prototype.settings.maps = {
  mapDefault: "1-1",
  locationDefault: "0",
  groupTypes: ["Character", "Solid", "Scenery", "Text"],
  requireEntrance: true,
  screenAttributes: [
    "gravity",
    "setting",
    "time",
    "underwater",
    "floor",
    "jumpmod",
    "maxyvel",
    "maxyvelinv",
    "notime",
    "nokeys",
    "canscroll",
  ],
  screenVariables: {
    bottomDeathDifference: function (EightBitter) {
      return EightBitter.unitsize * 12;
    },
    bottomPlatformMax: function (EightBitter) {
      var area = EightBitter.MapsHandler.getArea(),
        diff = EightBitter.MapScreener.bottomDeathDifference;

      if (!area) {
        return -1;
      }

      return (area.floor + diff) * EightBitter.unitsize;
    },
    gravity: function (EightBitter) {
      var area = EightBitter.MapsHandler.getArea();

      if (area && area.underwater) {
        return EightBitter.gravity / 2.8;
      }

      return EightBitter.gravity;
    },
  },
  onSpawn: FullScreenMario.prototype.addPreThing,
  macros: {
    Example: FullScreenMario.prototype.macroExample,
    Fill: FullScreenMario.prototype.macroFillPreThings,
    Pattern: FullScreenMario.prototype.macroFillPrePattern,
    Floor: FullScreenMario.prototype.macroFloor,
    Pipe: FullScreenMario.prototype.macroPipe,
    PipeCorner: FullScreenMario.prototype.macroPipeCorner,
    Tree: FullScreenMario.prototype.macroTree,
    Shroom: FullScreenMario.prototype.macroShroom,
    Water: FullScreenMario.prototype.macroWater,
    CastleSmall: FullScreenMario.prototype.macroCastleSmall,
    CastleLarge: FullScreenMario.prototype.macroCastleLarge,
    Ceiling: FullScreenMario.prototype.macroCeiling,
    Bridge: FullScreenMario.prototype.macroBridge,
    Scale: FullScreenMario.prototype.macroScale,
    PlatformGenerator: FullScreenMario.prototype.macroPlatformGenerator,
    WarpWorld: FullScreenMario.prototype.macroWarpWorld,
    CheepsStart: FullScreenMario.prototype.macroCheepsStart,
    CheepsStop: FullScreenMario.prototype.macroCheepsStop,
    BulletBillsStart: FullScreenMario.prototype.macroBulletBillsStart,
    BulletBillsStop: FullScreenMario.prototype.macroBulletBillsStop,
    LakituStop: FullScreenMario.prototype.macroLakituStop,
    StartInsideCastle: FullScreenMario.prototype.macroStartInsideCastle,
    EndOutsideCastle: FullScreenMario.prototype.macroEndOutsideCastle,
    EndInsideCastle: FullScreenMario.prototype.macroEndInsideCastle,
    Section: FullScreenMario.prototype.macroSection,
    SectionPass: FullScreenMario.prototype.macroSectionPass,
    SectionFail: FullScreenMario.prototype.macroSectionFail,
    SectionDecider: FullScreenMario.prototype.macroSectionDecider,
  },
  entrances: {
    Normal: FullScreenMario.prototype.mapEntranceNormal,
    Plain: FullScreenMario.prototype.mapEntrancePlain,
    Castle: FullScreenMario.prototype.mapEntranceCastle,
    Walking: FullScreenMario.prototype.mapEntranceWalking,
    Vine: FullScreenMario.prototype.mapEntranceVine,
    PipeVertical: FullScreenMario.prototype.mapEntrancePipeVertical,
    PipeHorizontal: FullScreenMario.prototype.mapEntrancePipeHorizontal,
  },
  patterns: (function (patterns) {
    var pattern, i;
    for (i in patterns) {
      if (patterns.hasOwnProperty(i)) {
        pattern = patterns[i];
        if (!pattern.length) {
          continue;
        }

        // Pattern's last array should previously be ["blank", width]
        pattern.width = pattern[pattern.length - 1][1];
        pattern.pop();
      }
    }
    return patterns;
  })({
    BackRegular: [
      ["HillLarge", 0, 0],
      ["Cloud1", 68, 68],
      ["Bush3", 92, 0],
      ["HillSmall", 128, 0],
      ["Cloud1", 156, 76],
      ["Bush1", 188, 0],
      ["Cloud3", 220, 68],
      ["Cloud2", 292, 76],
      ["Bush2", 332, 0],
      ["Blank", 384],
    ],
    BackCloud: [
      ["Cloud2", 28, 64],
      ["Cloud1", 76, 32],
      ["Cloud2", 148, 72],
      ["Cloud1", 228, 0],
      ["Cloud1", 284, 32],
      ["Cloud1", 308, 40],
      ["Cloud1", 372, 0],
      ["Blank", 384],
    ],
    BackFence: [
      ["PlantSmall", 88, 0],
      ["PlantLarge", 104, 0],
      ["Fence", 112, 0, 32],
      ["Cloud1", 148, 68],
      ["PlantLarge", 168, 0],
      ["PlantSmall", 184, 0],
      ["PlantSmall", 192, 0],
      ["Cloud1", 220, 76],
      ["Cloud2", 244, 68],
      ["Fence", 304, 0, 16],
      ["PlantSmall", 320, 0],
      ["Fence", 328, 0],
      ["PlantLarge", 344, 0],
      ["Cloud1", 364, 76],
      ["Cloud2", 388, 68],
      ["Blank", 384],
    ],
    BackFenceMin: [
      ["PlantLarge", 104, 0],
      ["Fence", 112, 0, 32],
      ["Cloud1", 148, 68],
      ["PlantLarge", 168, 0],
      ["PlantSmall", 184, 0],
      ["PlantSmall", 192, 0],
      ["Cloud1", 220, 76],
      ["Cloud2", 244, 68],
      ["Fence", 304, 0, 16],
      ["PlantSmall", 320, 0],
      ["Fence", 328, 0],
      ["Cloud1", 364, 76],
      ["Cloud2", 388, 68],
      ["Blank", 384],
    ],
    BackFenceMin2: [
      ["Cloud2", 4, 68],
      ["PlantSmall", 88, 0],
      ["PlantLarge", 104, 0],
      ["Fence", 112, 0],
      ["Fence", 128, 0, 16],
      ["Cloud1", 148, 68],
      // ["PlantLarge", 168, 0],
      ["PlantSmall", 184, 0],
      ["PlantSmall", 192, 0],
      ["Cloud1", 220, 76],
      ["Cloud2", 244, 68],
      ["Fence", 304, 0, 16],
      ["PlantSmall", 320, 0],
      ["Fence", 328, 0],
      ["PlantLarge", 344, 0],
      ["Cloud1", 364, 76],
      ["Cloud2", 388, 68],
      ["Blank", 384],
    ],
    BackFenceMin3: [
      ["Cloud2", 4, 68],
      ["PlantSmall", 88, 0],
      ["PlantLarge", 104, 0],
      ["Fence", 112, 0, 4],
      ["Cloud1", 148, 68],
      ["PlantSmall", 184, 0],
      ["PlantSmall", 192, 0],
      ["Cloud1", 220, 76],
      ["Cloud2", 244, 68],
      ["Cloud1", 364, 76],
      ["Cloud2", 388, 68],
      ["Blank", 384],
    ],
  }),
  library: (function (maps) {
    var library = {},
      i;

    for (i = 0; i < maps.length; i += 1) {
      library[maps[i].name] = maps[i];
    }

    return library;
  })([
    {
      name: "1-1",
      locations: [
        {
          entry: "Plain",
          area: "1",
        },
        {
          entry: "Plain",
          area: "0",
        },
      ],
      areas: [
        {
          setting: "Overworld",
          creation: [
            {macro: "Fill",x: 8,y: 8,thing: "BrickPlain",xnum: 5,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 8,y: 32,thing: "Stone",xnum: 5,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {thing: "Stone",x: 48,y: 24,width: 8,height: 8,
            },
            {thing: "Stone",x: 48,y: 32,width: 8,height: 8,
            },
            {thing: "Stone",x: 0,y: 24,width: 8,height: 8,
            },
            {thing: "Stone",x: 0,y: 32,width: 8,height: 8,
            },
            {thing: "Pipe",x: 16,y: 56,height: 16,
            },
            {macro: "Fill",x: 24,y: 48,thing: "Stone",xnum: 2,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 8,y: 8,thing: "Brick",xnum: 1,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {thing: "Cloud1",x: 20,y: 68,
            },
            {thing: "Cloud2",x: 28,y: 80,
            },
            {thing: "Cloud3",x: 40,y: 88,
            },
            {thing: "Cloud1",x: 28,y: 72,
            },
            {thing: "Cloud2",x: 24,y: 76,
            },
            {macro: "Shroom",x: 80,y: 56,width: 32,
            },
            {macro: "Shroom",x: 116,y: 24,width: 24,
            },
            {macro: "Shroom",x: 92,y: 80,width: 48,
            },
            {macro: "Shroom",x: 144,y: 44,width: 32,
            },
            {macro: "Shroom",x: 164,y: 68,width: 64,
            },
            {macro: "Shroom",x: 200,y: 28,width: 24,
            },
            {macro: "Shroom",x: 224,y: 52,width: 24,
            },
            {thing: "Fence",x: 48,y: 8,width: 44,
            },
            {thing: "Koopa",x: 194,y: 80,smart: true,jumping: false,flying: false,
            },
            {macro: "Fill",x: 118,y: 32,thing: "Coin",xnum: 3,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 174,y: 76,thing: "Coin",xnum: 4,ynum: 1,xwidth: 12,ywidth: 8,
            },
            {thing: "Block",x: 112,y: 100,contents: "Mushroom",hidden: false,
            },
            {macro: "Water",x: 268,y: -4,width: 200,
            },
            {thing: "Cloud1",x: 146,y: 88,
            },
            {thing: "Cloud1",x: 202,y: 52,
            },
            {thing: "Cloud1",x: 126,y: 56,
            },
            {thing: "Cloud2",x: 214,y: 84,
            },
            {thing: "Cloud1",x: 262,y: 64,
            },
            {thing: "Cloud1",x: 322,y: 32,
            },
            {thing: "Cloud1",x: 366,y: 72,
            },
            {thing: "Cloud2",x: 358,y: 44,
            },
            {thing: "Cloud3",x: 306,y: 84,
            },
            {thing: "Koopa",x: 124,y: 36,smart: true,jumping: false,flying: false,
            },
            {thing: "Koopa",x: 388,y: 72,smart: true,jumping: false,flying: false,
            },
            {thing: "Pipe",x: 282,y: 12,height: 64,
            },
            {thing: "Pipe",x: 314,y: 28,height: 64,
            },
            {macro: "Pipe",x: 362,y: -12,height: 40,piranha: true,
            },
            {thing: "Pipe",x: 402,y: 12,height: 64,
            },
            {macro: "Tree",x: 438,y: 20,width: 32,
            },
            {thing: "Block",x: 252,y: 24,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 450,y: 44,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 498,y: 28,contents: "Coin",
            },
            {thing: "Brick",x: 522,y: 28,contents: "Coin",
            },
            {thing: "Block",x: 506,y: 28,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 514,y: 28,contents: "Coin",hidden: false,
            },
            {thing: "Springboard",x: 522,y: 36,
            },
            {thing: "Brick",x: 546,y: 60,contents: "",
            },
            {thing: "Brick",x: 554,y: 60,contents: "",
            },
            {thing: "Brick",x: 562,y: 60,contents: "",
            },
            {thing: "Brick",x: 570,y: 60,contents: "",
            },
            {thing: "Bush3",x: 476,y: 4,
            },
            {thing: "Bush1",x: 438,y: 28,
            },
            {thing: "PlantLarge",x: 522,y: 16,
            },
            {thing: "PlantLarge",x: 578,y: 16,
            },
            {thing: "PlantSmall",x: 558,y: 8,
            },
            {thing: "Fence",x: 546,y: 68,width: 32,
            },
            {thing: "Cloud3",x: 478,y: 80,
            },
            {thing: "Cloud2",x: 566,y: 88,
            },
            {thing: "Cloud2",x: 402,y: 96,
            },
            {thing: "Block",x: 156,y: 28,contents: "Mushroom1Up",hidden: true,
            },
            {macro: "Tree",x: 568,y: 48,width: 48,
            },
            {thing: "Bush1",x: 540,y: 4,
            },
            {thing: "Bush2",x: 592,y: 56,
            },
            {thing: "PlantLarge",x: 582,y: 68,
            },
            {thing: "Brick",x: 468,y: 4,contents: "",
            },
            {thing: "Brick",x: 588,y: 4,contents: "",
            },
            {thing: "Coin",x: 320,y: 36,
            },
            {thing: "Coin",x: 288,y: 20,
            },
            {thing: "Coin",x: 408,y: 20,
            },
            {macro: "Tree",x: 586,y: 24,width: 96,
            },
            {thing: "Coin",x: 546,y: 88,
            },
            {thing: "Coin",x: 572,y: 88,
            },
            {thing: "Bush3",x: 650,y: 32,
            },
            {thing: "Bush2",x: 610,y: 32,
            },
            {thing: "PlantSmall",x: 638,y: 36,
            },
            {thing: "Floor",x: 0,y: 0,width: 272,height: 14,
            },
            {thing: "Floor",x: 468,y: -4,width: 128,height: 8,
            },
            {thing: "Piranha",x: 596,y: 36,evil: false,
            },
            {thing: "Piranha",x: 628,y: 36,evil: false,
            },
            {thing: "Piranha",x: 664,y: 36,evil: false,
            },
            {thing: "Goomba",x: 566,y: 16,
            },
            {thing: "Cloud3",x: 638,y: 76,
            },
            {macro: "Fill",x: 684,y: -4,thing: "BrickPlain",xnum: 3,ynum: 5,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 684,y: 36,thing: "BrickPlain",xnum: 1,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 700,y: 36,thing: "BrickPlain",xnum: 1,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 684,y: 52,thing: "BrickPlain",xnum: 3,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 676,y: 60,thing: "BrickPlain",xnum: 5,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 676,y: 68,thing: "BrickPlain",xnum: 1,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 692,y: 68,thing: "BrickPlain",xnum: 1,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 708,y: 68,thing: "BrickPlain",xnum: 1,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 758,y: -4,thing: "BrickPlain",xnum: 3,ynum: 8,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 758,y: 60,thing: "BrickPlain",xnum: 1,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 774,y: 60,thing: "BrickPlain",xnum: 1,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 758,y: 76,thing: "BrickPlain",xnum: 3,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 750,y: 84,thing: "BrickPlain",xnum: 5,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 750,y: 92,thing: "BrickPlain",xnum: 3,ynum: 1,xwidth: 16,ywidth: 8,
            },
            {macro: "Scale",x: 696,y: 48,widthLeft: 24,widthRight: 24,between: 76,dropLeft: 24,dropRight: 24,
            },
            {macro: "Pipe",x: 726,y: -12,height: 36,piranha: true,
            },
            {macro: "Bridge",x: 804,y: 16,width: 80,start: true,end: true,
            },
            {macro: "Fill",x: 796,y: -8,thing: "Stone",xnum: 1,ynum: 4,xwidth: 8,ywidth: 8,
            },
            {thing: "Koopa",x: 868,y: 32,smart: true,jumping: false,flying: false,
            },
            {thing: "Coin",x: 806,y: 28,
            },
            {thing: "Coin",x: 810,y: 36,
            },
            {thing: "Coin",x: 814,y: 44,
            },
            {thing: "Coin",x: 818,y: 36,
            },
            {thing: "Coin",x: 822,y: 28,
            },
            {thing: "Coin",x: 862,y: 28,
            },
            {thing: "Coin",x: 858,y: 36,
            },
            {thing: "Coin",x: 862,y: 44,
            },
            {thing: "Coin",x: 866,y: 36,
            },
            {thing: "Block",x: 836,y: 44,contents: "Coin",hidden: false,
            },
            {macro: "Fill",x: 908,y: 44,thing: "Brick",xnum: 14,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 908,y: 68,thing: "BrickPlain",xnum: 3,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 996,y: 68,thing: "BrickPlain",xnum: 3,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 952,y: 68,thing: "BrickPlain",xnum: 3,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {thing: "Coin",x: 694,y: 32,
            },
            {thing: "Coin",x: 770,y: 32,
            },
            {thing: "Coin",x: 732,y: 32,
            },
            {thing: "Coin",x: 966,y: 16,
            },
            {thing: "Coin",x: 974,y: 16,
            },
            {thing: "Cannon",x: 1036,y: 24,height: 40,
            },
            {thing: "Cannon",x: 1044,y: 32,height: 50,
            },
            {thing: "Cloud3",x: 818,y: 88,
            },
            {thing: "Cloud2",x: 710,y: 84,
            },
            {thing: "Fence",x: 766,y: 68,width: 8,
            },
            {thing: "Fence",x: 766,y: 60,width: 8,
            },
            {thing: "Fence",x: 692,y: 36,width: 8,
            },
            {thing: "Fence",x: 692,y: 44,width: 8,
            },
            {thing: "Cloud1",x: 934,y: 76,
            },
            {thing: "HillLarge",x: 794,y: 0,
            },
            {thing: "HillSmall",x: 878,y: -4,
            },
            {thing: "HillSmall",x: 856,y: -4,
            },
            {thing: "HillLarge",x: 832,y: -4,
            },
            {thing: "HillLarge",x: 816,y: 4,
            },
            {thing: "HillLarge",x: 718,y: 4,
            },
            {thing: "HillSmall",x: 710,y: -4,
            },
            {thing: "Coin",x: 1030,y: 24,
            },
            {thing: "Coin",x: 1038,y: 32,
            },
            {thing: "Coin",x: 1046,y: 40,
            },
            {thing: "Floor",x: 1052,y: 32,width: 240,height: 45,
            },
            {macro: "Water",x: 1292,y: 12,width: 400,
            },
            {thing: "Block",x: 1068,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 1084,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 1076,y: 56,contents: "",
            },
            {thing: "Brick",x: 1076,y: 80,contents: "",
            },
            {thing: "FireFlower",x: 1076,y: 88,
            },
            {thing: "Platform",x: 1158,y: 60,width: 20,
            },
            {thing: "Platform",x: 1188,y: 76,width: 20,
            },
            {macro: "Fill",x: 908,y: 16,thing: "Brick",xnum: 6,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 980,y: 16,thing: "Brick",xnum: 7,ynum: 1,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 908,y: -8,thing: "Brick",xnum: 16,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {thing: "Coin",x: 958,y: 16,
            },
            {thing: "Koopa",x: 1198,y: 88,smart: false,jumping: false,flying: false,
            },
            {thing: "Koopa",x: 1186,y: 88,smart: true,jumping: true,flying: true,
            },
            {macro: "EndOutsideCastle",x: 1218,y: 32,transport: {  map: "1-2",},
            },
          ],
        },
        {
          setting: "Overworld",
          creation: [
            {macro: "Fill",x: 0,y: -8,thing: "Floor",xnum: 30,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 48,y: 8,thing: "Floor",xnum: 1,ynum: 2,xwidth: 8,ywidth: 8,
            },
            {thing: "PipeHorizontal",x: 32,y: 16,width: 16,transport: "1",
            },
            {thing: "PlantLarge",x: 80,y: 20,
            },
            {thing: "PlantLarge",x: 280,y: 20,
            },
            {thing: "PlantLarge",x: 215,y: 20,
            },
            {thing: "PlantLarge",x: 166,y: 20,
            },
            {thing: "PlantSmall",x: 110,y: 12,
            },
            {thing: "PlantSmall",x: 72,y: 12,
            },
            {thing: "PlantSmall",x: 174,y: 12,
            },
            {thing: "PlantSmall",x: 204,y: 12,
            },
            {thing: "PlantSmall",x: 254,y: 12,
            },
            {thing: "Fence",x: 260,y: 8,width: 80,
            },
            {macro: "Fill",x: 0,y: 24,thing: "Floor",xnum: 7,ynum: 1,xwidth: 8,ywidth: 8,
            },
            { macro: "Pattern", pattern: "BackRegular", repeat: 5 },
            { macro: "Floor", width: 552 },
            { thing: "DecorativeBack", x: 90, y: 88 },
            { thing: "DecorativeDot", x: 91.5, y: 46.5 },
            { thing: "DecorativeDot", x: 91.5, y: 86.5 },
            {thing: "CustomText",x: 90,y: 36,texts: [  { text: "MOVE: ARROWS/WASD", offset: 12 },  { text: "FIRE/SPRINT: SHIFT/CTRL" },  { text: "PAUSE: P/RIGHTCLICK", offset: 8 },],
            },
            {thing: "CustomText",x: 94.5,y: 84,size: "Large",texts: [{ text: "SUPER" }],
            },
            {thing: "CustomText",x: 94.5,y: 68,size: "Huge",texts: [{ text: "MARIO BROS." }],
            },
            { thing: "DecorativeDot", x: 175.5, y: 46.5 },
            { thing: "DecorativeDot", x: 175.5, y: 86.5 },
            {thing: "CustomText",x: 122,y: 44,size: "Colored",texts: [{ text: "©1985 NINTENDO" }],
            },
          ],
        },
      ],
      time: "400",
    },
    {
      name: "1-2",
      locations: [
        {
          entry: "Normal",
          area: "0",
        },
        {
          entry: "Normal",
          area: "1",
        },
      ],
      areas: [
        {
          setting: "Castle",
          creation: [
            { macro: "Floor", x: 0, y: 0, width: 300 },
            { thing: "Floor", x: 126, y: 32, width: 160, height: 8 },
            { thing: "Springboard", x: 144, y: 44 },
            { thing: "Floor", x: 152, y: 72, width: 136, height: 8 },
            { thing: "Block", x: 262, y: 56, contents: "Coin", hidden: false },
            { thing: "Brick", x: 254, y: 56, contents: "" },
            { thing: "Block", x: 246, y: 56, contents: "", hidden: false },
            { thing: "Brick", x: 212, y: 56, contents: "" },
            { thing: "Block", x: 220, y: 56, contents: "Coin", hidden: false },
            {thing: "Block",x: 204,y: 56,contents: "Mushroom1Up",hidden: true,
            },
            {thing: "Blooper",x: 360,y: 52,
            },
            {thing: "Koopa",x: 278,y: 84,smart: true,jumping: false,flying: false,
            },
            {thing: "Coin",x: 178,y: 80,
            },
            {thing: "Coin",x: 184,y: 88,
            },
            {thing: "Coin",x: 190,y: 80,
            },
            {thing: "Coin",x: 252,y: 80,
            },
            {thing: "Coin",x: 260,y: 80,
            },
            {thing: "Coin",x: 268,y: 80,
            },
            {thing: "Coin",x: 176,y: 8,
            },
            {thing: "Coin",x: 184,y: 8,
            },
            {thing: "Coin",x: 192,y: 8,
            },
            {thing: "Goomba",x: 272,y: 8,
            },
            {macro: "Water",x: 300,y: -4,width: 160,
            },
            {macro: "Pipe",x: 328,y: -12,height: 32,piranha: false,
            },
            {macro: "Pipe",x: 380,y: -12,height: 40,piranha: true,
            },
            {thing: "Block",x: 64,y: 32,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 72,y: 32,contents: "",
            },
            {thing: "Block",x: 72,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 80,y: 56,contents: "",
            },
            {thing: "Block",x: 80,y: 80,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 96,y: 32,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 88,y: 32,contents: "",
            },
            {thing: "Beetle",x: 96,y: 40,
            },
            {thing: "Floor",x: 460,y: 20,width: 320,height: 32,
            },
            {thing: "Block",x: 80,y: 32,contents: "Mushroom",hidden: false,
            },
            {thing: "Block",x: 88,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "FireFlower",x: 80,y: 88,
            },
            {thing: "Podoboo",x: 312,y: -4,
            },
            {thing: "Podoboo",x: 360,y: -4,
            },
            {thing: "Podoboo",x: 412,y: -4,
            },
            {thing: "Podoboo",x: 432,y: -4,
            },
            {macro: "Scale",x: 408,y: 72,widthLeft: 12,widthRight: 12,between: 32,dropLeft: 40,dropRight: 40,
            },
            {macro: "Fill",x: 406,y: 36,thing: "Coin",xnum: 1,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 438,y: 36,thing: "Coin",xnum: 1,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {thing: "HammerBro",x: 740,y: 32,
            },
            {macro: "Fill",x: 496,y: 28,thing: "BrickPlain",xnum: 3,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 572,y: 28,thing: "BrickPlain",xnum: 3,ynum: 5,xwidth: 8,ywidth: 8,
            },
            {macro: "Fill",x: 654,y: 28,thing: "BrickPlain",xnum: 3,ynum: 3,xwidth: 8,ywidth: 8,
            },
            {macro: "Pipe",x: 538,y: 20,height: 24,piranha: true,
            },
            {thing: "Beetle",x: 522,y: 28,
            },
            {thing: "Block",x: 530,y: 44,contents: "MushroomDeathly",hidden: true,
            },
            {thing: "Block",x: 522,y: 44,contents: "MushroomDeathly",hidden: true,
            },
            {thing: "Block",x: 504,y: 44,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 496,y: 44,contents: "",
            },
            {thing: "Brick",x: 512,y: 44,contents: "",
            },
            {thing: "Platform",x: 572,y: 60,width: 24,
            },
            {thing: "Block",x: 662,y: 44,contents: "MushroomDeathly",hidden: false,
            },
            {thing: "Brick",x: 654,y: 44,contents: "Coin",
            },
            {thing: "Brick",x: 670,y: 44,contents: "Coin",
            },
            {thing: "Brick",x: 580,y: 88,contents: "Star",
            },
            {thing: "Block",x: 580,y: 48,contents: "Mushroom1Up",hidden: true,
            },
            {thing: "Coin",x: 532,y: 28,
            },
            {thing: "Coin",x: 556,y: 28,
            },
            {thing: "Coin",x: 582,y: 76,
            },
            {thing: "Coin",x: 656,y: 52,
            },
            {thing: "Coin",x: 664,y: 52,
            },
            {thing: "Coin",x: 672,y: 52,
            },
            {thing: "Springboard",x: 772,y: 32,
            },
            {thing: "PipeHorizontal",x: 834,y: 20,width: 16,
            },
            {thing: "Floor",x: 850,y: 28,width: 80,height: 40,
            },
            {thing: "Block",x: 884,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 892,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 876,y: 56,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 900,y: 56,contents: "",
            },
            {thing: "Brick",x: 868,y: 5,contents: "",
            },
            {thing: "Brick",x: 868,y: 56,contents: "",
            },
            {thing: "Block",x: 884,y: 84,contents: "MushroomDeathly",hidden: false,
            },
            {thing: "Cannon",x: 952,y: 40,height: 55,
            },
            {thing: "Cannon",x: 978,y: 48,height: 65,
            },
            {macro: "Scale",x: 1054,y: 68,widthLeft: 20,widthRight: 20,between: 120,dropLeft: 36,dropRight: 28,
            },
            {macro: "Pipe",x: 1112,y: -8,height: 56,piranha: false,
            },
            {macro: "Pipe",x: 1128,y: -8,height: 56,piranha: true,
            },
            {thing: "Coin",x: 1118,y: 56,
            },
            {thing: "Coin",x: 1118,y: 64,
            },
            {thing: "Block",x: 1116,y: 80,contents: "Coin",hidden: false,
            },
            {thing: "Podoboo",x: 1052,y: -4,
            },
            {macro: "Water",x: 930,y: -4,width: 400,
            },
            {thing: "Floor",x: 1330,y: 28,width: 160,height: 40,
            },
            {thing: "Koopa",x: 1474,y: 40,smart: true,jumping: true,flying: true,
            },
            {thing: "Koopa",x: 1454,y: 40,smart: true,jumping: true,flying: true,
            },
            {thing: "Coin",x: 1348,y: 36,
            },
            {thing: "Coin",x: 1356,y: 36,
            },
            {thing: "Coin",x: 1364,y: 36,
            },
            {thing: "Block",x: 1386,y: 52,contents: "Coin",hidden: false,
            },
            {thing: "Block",x: 1394,y: 52,contents: "Coin",hidden: false,
            },
            {thing: "Brick",x: 1390,y: 76,contents: "Mushroom",
            },
            {thing: "Brick",x: 1434,y: 52,contents: "",
            },
            {thing: "Brick",x: 1426,y: 52,contents: "",
            },
            {thing: "Brick",x: 1418,y: 52,contents: "",
            },
            {thing: "Floor",x: 1490,y: 60,width: 160,height: 72,
            },
            {thing: "Coin",x: 1392,y: 84,
            },
            {thing: "Coin",x: 1428,y: 60,
            },
            {thing: "Coin",x: 1412,y: 52,
            },
            {thing: "Coin",x: 1444,y: 52,
            },
            {thing: "Coin",x: 1482,y: 36,
            },
            {thing: "Block",x: 1426,y: 76,contents: "MushroomDeathly",hidden: true,
            },
            {thing: "Block",x: 1418,y: 76,contents: "MushroomDeathly",hidden: true,
            },
            {thing: "Block",x: 1436,y: 76,contents: "MushroomDeathly",hidden: true,
            },
            {thing: "CastleBridge",x: 1250,y: 28,width: 80,
            },
            {thing: "Podoboo",x: 1150,y: -4,
            },
            {thing: "Podoboo",x: 1194,y: -4,
            },
            {thing: "Podoboo",x: 1242,y: -4,
            },
            {thing: "Beetle",x: 1298,y: 36,
            },
            {thing: "CheepCheep",x: 1616,y: 68,smart: true,
            },
            {thing: "Beetle",x: 1628,y: 68,
            },
            {macro: "Fill",x: 1526,y: 68,thing: "Coin",xnum: 6,ynum: 1,xwidth: 16,ywidth: 8,
            },
            {macro: "Scale",x: 1086,y: 80,widthLeft: 20,widthRight: 20,between: 140,dropLeft: 40,dropRight: 60,
            },
            {thing: "Brick",x: 1104,y: 28,contents: "",
            },
            {thing: "Brick",x: 1096,y: 28,contents: "",
            },
            {thing: "Platform",x: 452,y: 4,width: 8,
            },
            {thing: "Stone",x: 236,y: 0,width: 8,height: 16,
            },
            {macro: "Water",x: 1648,y: 16,width: 124,
            },
            {thing: "CastleBridge",x: 1650,y: 40,width: 122.8,
            },
            {thing: "Cloud3",x: 2052,y: 44,
            },
            {thing: "Cloud3",x: 2008,y: 76,
            },
            {thing: "Cloud3",x: 2068,y: 92,
            },
            {thing: "Cloud2",x: 2072,y: 64,
            },
            {thing: "Cloud1",x: 2044,y: 88,
            },
            {thing: "PlantLarge",x: 2020,y: 40,
            },
            {thing: "PlantSmall",x: 2004,y: 32,
            },
            {thing: "HillLarge",x: 2048,y: 0,
            },
            {thing: "HillSmall",x: 2032,y: -4,
            },
            {thing: "HillLarge",x: 2080,y: 0,
            },
            {thing: "HillLarge",x: 2064,y: -4,
            },
            {thing: "HillSmall",x: 2108,y: -4,
            },
            {thing: "HillSmall",x: 2128,y: -4,
            },
            {thing: "Fence",x: 2014,y: 24,width: 8,
            },
            {thing: "Platform",x: 986,y: 40,width: 28,
            },
            {macro: "EndInsideCastle",x: 1772,y: 16,spawnType: "Bowser",transport: {  map: "1-1",},
            },
            {thing: "PipeHorizontal",x: 2012.5,y: 32,width: 16,transport: "1",
            },
            {thing: "Floor",x: 2028.5,y: 52,width: 8,height: 64,
            },
          ],
        },
        {
          setting: "Overworld",
          creation: [
            {thing: "Floor",x: 0,y: 20,width: 80,height: 32,
            },
            {thing: "CustomText",x: 20,y: 70,texts: [  {    text: "YOU WIN!!!",    offset: 12,  },],
            },
            {thing: "HillLarge",x: 20,y: 36,
            },
            {thing: "PlantLarge",x: 72,y: 40,
            },
            {thing: "Cloud3",x: 100,y: 52,
            },
            {thing: "Cloud1",x: 92,y: 76,
            },
            {thing: "Cloud3",x: 148,y: 88,
            },
            {thing: "Cloud2",x: 44,y: 88,
            },
            {macro: "Shroom",x: 112,y: 32,width: 32,
            },
            {macro: "Water",x: 80,y: 16,width: 400,
            },
            {thing: "Fence",x: 56,y: 28,width: 16,
            },
            {thing: "PlantSmall",x: 20,y: 32,
            },
            {thing: "Cloud3",x: 176,y: 56,
            },
            {thing: "Cloud2",x: 148,y: 64,
            },
            {thing: "Cloud2",x: 216,y: 88,
            },
            {thing: "Cloud1",x: 212,y: 72,
            },
            {thing: "Cloud1",x: 264,y: 52,
            },
            {thing: "Cloud1",x: 288,y: 80,
            },
            {macro: "Shroom",x: 182,y: 72,width: 24,
            },
            {macro: "Shroom",x: 218,y: 24,width: 40,
            },
          ],
        },
      ],
    },
  ]),
};
